### ISSUE TITLE
Package update

### ISSUE THREAD

**Issue by JTronLabs** [HiFaraz/atom-starter-pack#2]
It appears ESLint > JSHint https://www.sitepoint.com/comparison-javascript-linting-tools/

Also I was using terminal-plus and it crashed on me a lot. Switched to PlatformIO-IDE-Terminal and it's more stable, and customizable https://atom.io/packages/platformio-ide-terminal

**Comment by JTronLabs** [comment]
But it's not configurable. That's a huge minus. My understanding is most projects use ESLint or JSHint. But more use ESLint over JSHint. Thus setting up with ESLint will be more compatible with most projects. Plus it's an easy thing to change later.

**Comment by HiFaraz** [comment]
Here's what I'm seeing:

* JSLint - old and can't be updated
* JSHint - works out of the box, can be configured
* ESLint - you need to globally install eslint, go through a config process that's not properly documented
* XO - ESLint with some defaults, not yet stable, needs to be installed as a dependency on your project

So I'm leaning towards not changing anything. We can follow the approach that as the developer outgrows JSHint they can find ESLint themselves. We don't need to give them their forever tool, only something that gets them started.

Thoughts?

**Comment by JTronLabs** [comment]
ESLint has [good documentation](http://eslint.org/docs/user-guide/configuring). Most stuff works out of the box and, most importantly, its easiest to configure (according to my first linked article). Just like Atom. If you don't want to change it, no big. 

> ESLint is the most recent out of the four. It was designed to be easily extensible, comes with a large number of custom rules, and it’s easy to install more in the form of plugins. It gives concise output, but includes the rule name by default so you always know which rules are causing the error messages.

**Comment by HiFaraz** [comment]
Even configuring JSHint to accept ES2015 is a big pain. I'm beginning to think this is something that's best  left to later in the developer's life.

**Comment by JTronLabs** [comment]
I disagree. Linters are really helpful and should be used from the get-go. It is also immediately helpful and helps transform Atom from text editor to IDE-lite. If you install linter and ESLint package in atom you should be good to go from the get-go. Try it out.

**Comment by HiFaraz** [comment]
I think I've figured it out. We need to add this to the workflow if we use ESLint:

* in your project directory, run `eslint --init` (guide is here: http://devnull.guru/adding-eslint-to-your-project-is-easier-than-ever/)

Seems like even when I pick Node the `no-console` rule is still enabled. Should we tell users to disable it, or direct them towards a proper logging package?

**Comment by JTronLabs** [comment]
Oh nice, good find. IDK what `no-console` rule is

**Comment by HiFaraz** [comment]
Yea that was the block for me - there was no guidance on how to answer those damn questions! lol

**Comment by HiFaraz** [comment]
Once you've tested #1 and we bump this up to v1.0, I'll add it to the playbook and add the workflow guidance too. Closing this now.
